name: Release nuget on tag

on:
  push:
    tags:
    - '*'

env:
  BUILD_CONFIGURATION: 'Release'    # set this to the appropriate build configuration

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.x
            7.x
            8.x

      # Run dotnet build and package
      - name: dotnet restore
        run: dotnet restore
          
      - name: dotnet build
        run: dotnet build --configuration '${{ env.BUILD_CONFIGURATION }}'

      - name: dotnet test
        run: dotnet test --configuration '${{ env.BUILD_CONFIGURATION }}'

  az-artifacts-build-and-deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.x
            7.x
            8.x
          source-url: ${{ env.AZURE_ARTIFACTS_FEED_URL }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.AZURE_DEVOPS_TOKEN }} 

      # Run dotnet build and package
      - name: dotnet restore
        run: dotnet restore
          
      - name: dotnet build
        run: dotnet build --configuration '${{ env.BUILD_CONFIGURATION }}'

      - name: dotnet pack
        run: dotnet pack -c '${{ env.BUILD_CONFIGURATION }}'

      # Publish the package to Azure Artifacts
      - name: 'dotnet publish'
        run: dotnet nuget push "**/src/Younited.HealthCheck.EntityFrameworkMigrations/bin/${{ env.BUILD_CONFIGURATION }}/*.nupkg" --api-key ${{ secrets.nuget_api_key }} --source https://api.nuget.org/v3/index.json